environment:
  min: [0.0, 0.0]
  max: [10.0, 10.0]
  obstacles:
    - [[1.0, 1.0], [1.0, 3.0], [3.0, 3.0], [3.0, 1.0]]
    - [[6.0, 6.0], [6.0, 8.0], [8.0, 8.0], [8.0, 6.0]]

robots:
  starts: 
    - [0.5, 0.5]
    - [9.5, 0.5]
    - [0.5, 9.5]
  goals:
    - [9.5, 9.5]
    - [0.5, 9.5]
    - [9.5, 0.5]
